site:
  name: Geode
  suffix: " - Geode"
  base_url: https://geode.rhmt.my.id

build:
  output: public
  mode: draft

theme: default

ignorePatterns:
  - .git
  - .obsidian
  - .trash

socials:
  - title: Discord
    link: https://discord.gg/y25Mm7dn
  - title: Github
    link: https://github.com/artsbymat
